version: "3"

services:
    main:
        build:
           context: main
        expose: 
            - 8080
        scale: 3

    companies:
        build:
           context: ktor-companies
        expose: 
            - 8080
        scale: 3
    
    countries:
        build:
           context: countries
        expose: 
            - 8080
        scale: 3

    nginx:
        container_name: balancer
        build:
            context: nginx
        ports:
            - "8000:8000"
        depends_on:
            - main
            - companies
            - countries
